#!/bin/bash

source /opt/ros/indigo/setup.bash
source /home/teamauv/ros_workspace/setup.bash


#/usr/bin/gnome-terminal -x sh -c "tmux new -s roscore '/opt/ros/indigo/bin/roscore'" 

#/usr/bin/gnome-terminal -x sh -c "/opt/ros/indigo/bin/roscore & "

#bash /home/teamauv/startup_scripts/roscore.sh 

bash /home/teamauv/startup_scripts/sensorstart.sh

#bash /home/teamauv/startup_scripts/roscore.sh & bash /home/teamauv/startup_scripts/sensorstart.sh
